### PR TITLE
Hotfix/0.11.1

### PR DESCRIPTION
**Pull request by pblittle**
This addresses #55. The issue was the sed `/` delimiter was failing when a URL was being evaluated. Changed the delimiter to `|`.

### CODE REVIEW

**Comment by systemfreund** [comment]
When are you going to merge this PR?

**Comment by pblittle** [comment]
@systemfreund the short answer is ASAP. I would like for someone to pull the `hotfix/0.11.1` branch and test before I release though. My test suite looks good, but I don't want to potentially miss an edge case. I'll merge as soon as I hear a confirmation.

**Comment by systemfreund** [comment]
I've built my own image from the hotfix/0.11.1 branch earlier. I'm currently using it without problems, so as for me you're good to go.

**Comment by pblittle** [comment]
@systemfreund are you using the embedded Elasticsearch or linked?

**Comment by systemfreund** [comment]
@pblittle  the linked one

**Comment by pblittle** [comment]
@jwalton, @systemfreund this was merged into `master` and tagged `rel-0.11.1` here on Github. I also tagged `latest` and `0.11.1` on DockerHub.

Thanks again for the help. Please let me know if you run into any issues.

**Pull request merged**
