### PR TITLE
Feature/Use custom patterns url

### PR DESCRIPTION
**Pull request by aidan-**
I recall reading somewhere that the future goal of this container is to download a tar/zip file of configuration but wasn't sure if that was going to include custom patterns or how far down the track that change will be.

For the time being I have added the mechanism to pull in a custom pattern file which get stored in `/opt/logstash/patterns/custom` similar to how the logstash.conf is pulled on container run.

### CODE REVIEW

**Comment by pblittle** [comment]
@aidan- thanks for this PR. I appreciate it. You're right about a future goal being a more robust way of managing logstash config files. The proposal is in issue #49. It is pretty hot for me and at the top of my to-do list. I am working on it now.

The way that feature is going to work is any asset (`*.tar`, `*.war`, `*.git`, etc) passed to `LOGSTASH_CONFIG_URL` will be downloaded and stored in `/opt/logstash/conf.d`. Correct me if I'm wrong, but, based on your PR, `/opt/logstash/conf.d` isn't the conventional location to store custom pattern files.

One thing you mentioned in your comment was your PR possibly being a temporarily solution while the bigger config feature is fleshed out. Is not having the ability to store patterns a blocker for you currently? If it is, then we can work towards getting it pulled in. If not, it might make sense to work through the bigger config management feature.

**Comment by aidan-** [comment]
Correct, generally patterns are stored in `/opt/logstash/patterns` (where my PR puts the custom file) rather than the `conf.d` directory.  However, the Grok filter allows you to define a patterns directory as one of its options (see [grok#patterns_dir](http://logstash.net/docs/1.4.2/filters/grok#patterns_dir)) so you could include custom patterns in the future asset archive functionality and just ensure the logstash config glob excludes those files (eg, `--config /op/logstash/conf.d/*.conf`).

I only referred to my PR as a possible 'temporary' solution as I was not sure what scope the future config archive feature was going to cover or how far away it was.  For me personally, a custom pattern feature is critical so we have been building a modified container with this PR applied to fill our requirements.

**Comment by pblittle** [comment]
@aidan- now we're getting somewhere. I think optionally including a `patterns` directory in the assets downloaded from `LOGSTASH_CONFIG_URL` will work really well. Additionally, the downloaded directory could include `inputs`, `outputs`, `filters`, etc.

I started a [logstash-configs](https://github.com/pblittle/logstash-configs) project last year for testing config downloads. That project can be used to test this new functionality.

I created a [feature/config-download-refactor](https://github.com/pblittle/docker-logstash/tree/feature/config-download-refactor) branch last night to track this feature. I'll merge in what I have so far either tomorrow or this weekend and we can see how far that gets us.

**Comment by aidan-** [comment]
@pblittle sounds good.  I will have a play/test once the changes have been merged in.

**Comment by pblittle** [comment]
@aidan- I haven't forgotten about this feature. It's up as soon as I ship #58.

**Comment by pblittle** [comment]
@aidan-, sorry, I thought I left a comment in your PR. This functionality should be taken care of in the [0.16.0](https://github.com/pblittle/docker-logstash/releases/tag/rel-0.16.0) release. You can find [the implementation details](https://github.com/pblittle/docker-logstash#logstash-configuration) in the documentation.

I'm going to close this PR for now. Please reopen or create a new issue if this doesn't fit the bill. Thanks again for your original PR that inspired this feature. I appreciate it.

**Pull request closed without merging**
